package com.zest.products.config;
import com.zest.products.auth.*; import io.jsonwebtoken.Claims; import jakarta.servlet.*; import jakarta.servlet.http.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.*; import org.springframework.http.HttpHeaders; import org.springframework.security.authentication.*; import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.core.userdetails.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.*; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.web.filter.OncePerRequestFilter; import org.springframework.stereotype.Component; import org.springframework.web.cors.*; import java.io.IOException; import java.util.*;
@Configuration @EnableMethodSecurity public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean UserDetailsService users(AppUserRepository repo){return username->repo.findByUsername(username).map(u->User.withUsername(u.getUsername()).password(u.getPassword()).authorities(u.getRoles().stream().map(role->new SimpleGrantedAuthority("ROLE_"+role)).toList()).build()).orElseThrow(()->new UsernameNotFoundException(username));}
 @Bean AuthenticationManager authenticationManager(AuthenticationConfiguration c)throws Exception{return c.getAuthenticationManager();}
 @Bean SecurityFilterChain security(HttpSecurity h,JwtFilter f,HttpsRedirectFilter https,CorsConfigurationSource cors)throws Exception{return h.csrf(c->c.disable()).cors(c->c.configurationSource(cors)).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/v1/auth/**","/swagger-ui/**","/swagger-ui.html","/v3/api-docs/**","/actuator/health").permitAll().anyRequest().authenticated()).addFilterBefore(https,UsernamePasswordAuthenticationFilter.class).addFilterBefore(f,UsernamePasswordAuthenticationFilter.class).build();}
 @Bean CorsConfigurationSource cors(@Value("${app.cors-origins}") String origins){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(Arrays.asList(origins.split(",")));c.setAllowedMethods(List.of("GET","POST","PUT","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("Authorization","Content-Type"));c.setMaxAge(3600L);UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
}
@Component class JwtFilter extends OncePerRequestFilter { private final JwtService jwt; JwtFilter(JwtService j){jwt=j;} @Override protected void doFilterInternal(HttpServletRequest r,HttpServletResponse response,FilterChain chain)throws ServletException,IOException {String h=r.getHeader(HttpHeaders.AUTHORIZATION);if(h!=null&&h.startsWith("Bearer "))try{Claims c=jwt.parse(h.substring(7)).getPayload();@SuppressWarnings("unchecked") List<String> roles=c.get("roles",List.class);var as=(roles==null?List.<String>of():roles).stream().map(x->new SimpleGrantedAuthority("ROLE_"+x)).toList();var a=new UsernamePasswordAuthenticationToken(c.getSubject(),null,as);SecurityContextHolder.getContext().setAuthentication(a);}catch(Exception ignored){}chain.doFilter(r,response);} }
@Component class HttpsRedirectFilter extends OncePerRequestFilter { private final boolean enforce; HttpsRedirectFilter(@Value("${app.enforce-https:false}") boolean enforce){this.enforce=enforce;} @Override protected void doFilterInternal(HttpServletRequest request,HttpServletResponse response,FilterChain chain)throws ServletException,IOException {if(enforce&&!request.isSecure()&&!"https".equalsIgnoreCase(request.getHeader("X-Forwarded-Proto"))){response.sendRedirect("https://"+request.getServerName()+request.getRequestURI());return;}chain.doFilter(request,response);} }
